### PR TITLE
feat: Added Docker and Docker Compose support

### PR DESCRIPTION
**Pull request by ivanskodje**
- Added Dockerfile
- Added docker-compose.yml
- Added .dockerignore
- Updated documentation to inform reader of how to get started using Docker and/or docker compose

### CODE REVIEW

**Comment by ixartz** [comment]
@ivanskodje Thank you for your PR and taking the time to implement the Docker support.
I'm really not a huge fan of Docker and it's overkill for this project. Especially, for a static blog. The project generate HTML files and it shouldn't have any compatibility issue.

The project doesn't have a server/backend logic.

**Comment by ivanskodje** [comment]
No problem. I understand that you may not be a fan of Docker and feel it may be overkill for this particular project, especially since this boilerplate is a _static_ blog generating HTML files without any server/backend logic, as you say.

However, considering that this project serves as a boilerplate for a blog, rather than a blog itself, it might be beneficial to include Docker support. Having Docker support doesn't mean you're obligated to use it if you prefer to host it as a static blog. It simply provides an additional option for those who may find it useful. :smile_cat: 

I'll do my best to share other improvements as I make them as well - it will of course be up to you whether or not you want to include it. 

You have done a great job with this project, thank you :star:

**Comment by ixartz** [comment]
@ivanskodje Extremely happy you made a PR and always looking for feedback and how we can improve the project. Today, there is a lot of hosting providers supporting Next.js: Vercel, Netlify, Amplify, Cloudflare, etc... It makes less mandatory to support Docker. Before, you are limited to Vercel but today, you have a tons of alternative. I feel using Docker is not anymore the mainstream way.

I also feel your docker implementation doesn't follow Next.js team best practices like using `standalone` output. So, you can a smaller Docker image.

**Comment by ixartz** [comment]
@ivanskodje If you have any other suggestion, extremely happy to hear it. If you don't want to lose your time, you can open an issue first before implementing and opening a PR.

**Pull request closed without merging**
